project_id = "pvgcrywkxzbgeywwhyqm"

[functions.calculate-similarity]
verify_jwt = false

[functions.predict-inventory]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.generate-product-content]
verify_jwt = false

[functions.sync-products-to-db]
verify_jwt = false